libretro/px68k-libretro

libretro.c, libretro/joystick.c
-Default 2 buttons
-CPSF-MD: 6 buttons Megadrive stick + up/down and left-right combos on start and select as they are not mapped. Maps directly to SF2' "SNES alike" (strong attacks on L & R)
Original stick mapping is ABC XYZ.
-CPSF-SFC: 8 buttons Super Famicom Joystick with a strange button placement YBA LXR.
Mapped it to corresponding Retropad letters to avoid confusion when trying to change keys in-game. 
(and 2 buttons games would work with retro_L and retro_A with the original mapping)
For 2 buttons default, changed A for jump, B for shoot/run.
Kept X & Y inverted so you can play SNES style vertically with A & X or B & Y in 2 different styles.
=> Add Joystick type core option

libretro.c, x68k/crtc.c
Most games use 55.45 fps, but others will use 61.46 . This should allow automatic-switch of fps depending on game.
Instead of using 61.46 for ->timing.fps, 59.94 is used to reduce audio stutters and other possible audio-related issues since most monitors run only at 60Hz.
=> Automatically switch refresh rates depending on game

libretro.c, libretro/winx68k.cpp
Stop using XVIMode as the change can get ignored if directly quitting without resuming the core session.
Can still be change in keropi/config.
The only difference between models, apart from clock speed, happens in x68/sysport.c.
=> Fix CPU Speed Option.

libretro/winx68k.cpp
Colon is now directly on the right of semicolon.
Minus and caret are right of 0.
0 didn't have a shift value while underscore was unmapped and is a shift value of an empty key.
Merged them together, 0+shift gives _.
The overlapping Japanese characters are not accessible as the kana/hiragana keys are unmapped, and shouldn't cause problem.
In line with neko project 2.
=> Some KB key fixes.

libretro.c
/home/buildbot/buildbot/android/libretro-px68k/libretro/jni/../../libretro.c:327:7: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
for (unsigned i = 0; i < size; i++)
=> android: buildfix

libretro.c
Add support for m3u playlist files for multi-disk games. The first 2 disks of the playlist are loaded into FDD0 and FDD1, respectively.
Also add disk swapping functions. As the X68000 had 2 x disk drives and some games require swapping disks in one or both drives the best solution I could think of to handle this was to add to add a core option that specifies which disk drive you are swapping disks on. 
Ideally, I think the RetroArch disk swap interface menu would allow swapping on more than one disk drive but as far as I can tell it is really only designed for one disk so the core option is the best workaround I can think of.
=> Add m3u playlist support and disk swapping functions.

libretro.c
Testing G-Sync by using the core at x1 speed I noticed some problems.
The sound was popping a lot at 55.45Hz so I tried to change it with different values I could find online.
It's fine with 55.5Hz.
That will maybe fix some crackles at different monitor refresh settings but that sadly doesn't help for stuck notes or overwritten samples we can seldom still hear.
Also switching to 59.94Hz wasn't working at x1, it stayed at 55.45Hz with the sound getting out of sync completely.
Using RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO fixes that.
It will cause a slight video re-init but it's the standard way to change the refresh rate in libretro.
=> Timing fixes.

win32api/dosio.c
strncpy() max size calculation on win32api/dosio.c is wrong.
For example in case curpath is ".//keropi/" (10 byte length), strncpy() append filename only 10byte.
It means reading BIOS ROM "iplrom.dat" will be success ( curpath ".//keropi/iplrom.dat" will be generated ) however, reading BIOS ROM "iplrom30.dat" will be fail ( curpath ".//keropi/iplrom30.d" will be generated ).
And if length of curpath is longher than `0.5*(MAX_PATH+32)` byte, strncpy() shall run over curpath buffer.
strncpy() max size must be smaller than `MAX_PATH + 32 - (curfilep - curpath)`. Considering 32 byte as safe margin, correct max size will be `MAX_PATH - (curfilep - curpath)`.
=> Fix wrong strncpy() size calculation of win32api/dosio.c

libretro.c, libretro/joystick.c, libretro/winx68k.cpp, x68k/mem_wrap.c
Stuff from retro-wertz.
-Recover 1 Frame of input lag.
-Simplify joypad type option and input handling
-Allow MEM map to use up to 12MB of memory
According to https://gamesx.com/wiki/doku.php?id=x68000:memory_map and Mame sources, x68000 should be able to use up to 12MB of memory. 
Current implementation only allowed 10MB max, selecting 11MB or 12MB resulted in bus errors.
=> Lag fix, Ram fix, joystick simplification.

Makefile.libretro
* This core has a mixed C/C++ codebase, therefore use `$(CXX)` as linker
Currently the builds are broken after recent commit 1848262
=> fix-build: Do not force linker to `$(CC)`

libretro.c
This gives priority to update_timing() over update_geometry() when both are triggered since update_timing() make use of RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO which re-initialize both geometry(width,height,aspect) and timing (fps/sound sample rate).
This is turn avoids causing both environment calls to be called in a single frame.
=> Give priority to update_timing() during AV changes

Makefile.libretro
* For `linux-arm7neonhf`, buildbot uses `platform=unix-armv7-hardfloat-neon` instead of `platform=unix`
Buildbot is currently failing for the `linux-arm7neonhf` target because the Makefile is incorrectly trying to match `platform` to exactly `unix` instead of partially. This PR fixes the issue and the build works now.
Tested build on Linux, ARM and Windows.
Ref: http://p.0bl.net/83594
=> fix-buildbot: Allow `platform` to be matched partially to `unix` instead of exactly

libretro_core_options.h
Most games won't run with 1MB and will display an issue in Japanese.
Better have it set to 2 by default.
=> 2MB default RAM size

libretro.c, libretro/joystick.c, libretro/keyboard.h, libretro/prop.h, libretro/winx68k.cpp, libretro_core_options.h
- as suggested by jfroco https://github.com/libretro/px68k-libretro/pull/81
"enable mapping of the select key of the joy1 to one of these keys: XF1, XF2, XF3, XF4, XF5, F1 or F2, configurable via Options
This allows to start this games using select key of the joy1:
Kyuukyoku Tiger (press XF3 to insert coin)
Parodius Da! (press F1 or F2 to start)"
- modified to match current code base
- also assigns keyboard keys OPT1 and OPT2
details : https://github.com/libretro/px68k-libretro/issues/89
@twinaphex
=> Joy1 select button key mapping (jfroco)

.gitignore, libretro.c, libretro/joystick.c, libretro/prop.c, libretro/prop.h, libretro_core_options.h
- (readability) descriptive cpu defines so branches specific for CYCLONE CPU and C68K are easily identifiable
- use libretro input bitmasks
- add core option to enable or disable saving disk path. this should prevent FDD drive from booting when user wants to start from a HDD drive
Reference PR, revised to be configurable rather than just disabled:
#58
Other related issues:
#38
=> core updates

libretro.c, libretro/windraw.c, libretro/winui.c, libretro_core_options.h
Items moved to core options:
- Frame Skip
- Joy/Mouse (mouse mode only works)
- Vbtn Swap
- No Wait Mode
Items that are disabled or removed, either because its not needed or its only using set-once option
- Sound Rate - fixed to 44100
- VKey Size - we dont use virtual keys
- HwJoy Setting - button mappings
- JoyKey, which is suppose to allow controlling gamepad buttons using a keyboard. Its not necessary in a libretro port due to how keyboard and joypad inputs already works.
=> Move menu items to core options

libretro.c
- When ejecting disk from disk control option, the signal is only sent to frontend and core does not
eject the disk when it should causing problems to some games that require only one disk to be inserted.
Reference issue: https://github.com/libretro/px68k-libretro/issues/98
=> Fix Disk Control not ejecting correctly for .m3u

libretro.c
- When option is set to "Joystick", the game should not respond to any more
mouse inputs. This is not the case due to a missing call to Mouse_StartCapture()
- From what i understand about this option, when "Joystick" is selected,
only joystick input would register with compatible games. When
"Mouse" is selected, both mouse and joystick inputs are registered to the game
(e.g. Granada).
Removing comment based on better understanding.
=> Fix Joy/Mouse core option's incorrect behavior

Makefile.libretro
Platform-defines uses -O2, but later on is overwritten with -O3. So
which one should be used?
PR changes this to use -O2 by default. Its faster at about 1-minute less
than using -O3 anyways so that probably means something.
=> Use -O2 optimization

libretro/windraw.c, libretro/winx68k.cpp, libretro/winx68k.h, x68k/bg.c, x68k/bg.h
hello.
RetroArch is crash with px68k, when playing "Phalanx_op.HDM" every time.
when change screen size , segmentation fault 11 is occur.
DWORD  is unsigned long ,  it can't mean "-1". (0xffffffff is not -1) .
and, translate few comment , japanese to english .
thanx
=> (DWORD)-1  problem

libretro.c
This should be enough of a fix. but the winmm midi driver appears to behave differently (maybe incorrectly) to initialize SC-55 and MT-32 properly.
SC-55 for example will have missing pitch/bend effects ans sometimes will hold notes longer than it should. in MT-32 it totally does not set some instruments properly. This issue is only a problem with using windows midi driver using the libretro API. Linux implementation works fine for the most part.
In anycase, short msg write should only be 3 bytes (suppose to be 2 bytes for midi status 0xC0 and 0xD0 but api does not like shorter than 3 writes) so this PR is still valid.
=> win32: Fix instruments not initializing (kinda)

libretro.c
=> Allow to change if midi type on reset instead of needing a core restart
