libretro.c
libretro/joystick.c
libretro/joystick.h
libretro/winx68k.cpp

Activated player 2.
Both players can choose a different joypad type in core options.

Add Joystick 2 with type core option.

---

libretro.c
libretro/winx68k.cpp

Works real time, interfaced with keropi/config.

Add Cpu Speed core option.

---

libretro.c
libretro/winx68k.cpp

We don't need to use switch.x anymore.
Default is 2MB.
All those "else if" in libretro.c could get rewritten in a better way.
I wasn't sure how to go from those DWORD to different values.

Select RAM Size as Core Option.

---

libretro/winx68k.cpp

Displayed after init.
Then again if a CPU/RAM change happens.

Log CPU and RAM changes.

---

x68k/disk_d88.c
x68k/disk_d88.h

Fix made by @retro-wertz 
They seem to run fine now, but he's not sure if that's the best way to do it?

D88 disk fix.

---

m68000/c68k/c68k_op9.inc

https://github.com/libretro/px68k-libretro/issues/30

Fix for Codezero crashing at startup logo

---

libretro.c
libretro/keyboard.c
libretro/winui.c
libretro/winx68k.cpp

This PR is to add some behavior-type logs like inserting disk, ejecting etc to help in troubleshooting.
Removed also some key-pressed related logs by wrapping them with #ifdef DEBUG and easier to enabled if needed to while limiting additional lines in log.

Update retro logs

---

fmgen/opna.cpp
libretro.c
libretro.h
libretro/joystick.c
libretro/joystick.h
libretro/windraw.c
libretro/winui.c
libretro/winui.h
libretro/winx68k.cpp
x68k/mercury.c

491f322 menu: Faster file/directory browsing
f857fb3 Prevent core from initializing more than 2 ports
a5af02b Update libretro header
6050066 Translate menu items to english
related topics:
https://github.com/libretro/px68k-libretro/issues/46
https://github.com/libretro/px68k-libretro/issues/41
https://github.com/libretro/px68k-libretro/issues/54

menu updates

---

libretro.c
x68k/sram.c

- Start core at higher frame rate
- Initialize SRAM with 0xFF

Minor tweaks

---

libretro_core_options.h

French translation  of all the menu and options

French translation

---

libretro-common/include/boolean.h
libretro-common/include/compat/msvc.h
libretro-common/include/compat/msvc/stdint.h
libretro-common/include/compat/strl.h
libretro-common/include/libretro.h
libretro-common/include/retro_common_api.h
libretro-common/include/string/stdstring.h
libretro.c

https://github.com/libretro/px68k-libretro/issues/118#issuecomment-577809866

Disk control interface v1 + custom labels

---

Makefile.libretro
fmgen/fmgen.cpp
libretro/common.h
libretro/winx68k.h
win32api/dosio.c
win32api/dosio.h
win32api/peace.c
win32api/windows.h

Reverts libretro/px68k-libretro#132

Revert "Added PS3 build"

---

fmgen/opna.cpp
libretro/windraw.c
win32api/windows.h
x68k/mem_wrap.c
x68k/x68kmemory.h

- Fix typedef warnings
- Fix some other warnings

Fix typedef issues

---

libretro.c
libretro/dswin.c
libretro/dswin.h
libretro/joystick.c
libretro/prop.c
libretro/prop.h
libretro/timer.c
libretro/winx68k.cpp
libretro_core_options.h
x68k/crtc.c

A couple fixes and added features with core options.  For the latter I was very careful to make sure the changes won't take effect unless explicitly enabled, that is default to old behavior for each.  I'd like to look into fixing some of the audio problems the core suffers from properly in the near future, but in the mean time I'm hoping my little 'hack" here gets accepted.

A few fixes and features

---

libretro_core_options_intl.h

The French translation have some issues:
- Options values are translated, which can break the core
- Added the missing translations

Fix french translation

---

libretro_core_options_intl.h

It seems PR #152 disappeared from master here, fixing it again.
If there is any issue, let me know.

Fix french language second round

---

libretro_core_options.h

Restore MIDI output core options

---

libretro.c

core should not be able to open zip files directly

Remove invalid extension (.zip)

---

.github/workflows/ci.yml

Add windows CI

---

x68k/adpcm.c
x68k/bg.c
x68k/crtc.c
x68k/fdc.c
x68k/gvram.c
x68k/mem_wrap.c
x68k/mercury.c
x68k/mfp.c
x68k/midi.c
x68k/pia.c
x68k/rtc.c
x68k/sasi.c
x68k/scc.c
x68k/scsi.c
x68k/tvram.c

some comments to English and cleanup
- covert encoding from jis/euc-jp to utf-8
- translate a few comments to english
- gvram: unroll gvram read/write function
- minor cleanups

x68k: Change file encoding from Shift JIS/EUC-JP to UTF-8, translate
